Makefile cleanup for service publication.

diff --git a/shared/monitor/Makefile b/shared/monitor/Makefile
--- a/shared/monitor/Makefile
+++ b/shared/monitor/Makefile
@@ -5,7 +5,6 @@ SERVICE_VERSION:="1.0.0"
 
 # Get the Open-Horizon architecture type, and IP address for this host
 ARCH:=$(shell ../../helper -a)
-HOST_IP:=$(shell ../../helper -i)
 
 #
 # Targets for building, developing, testing and cleaning this service
@@ -41,7 +40,7 @@ clean: validate-dockerhubid
 # NOTE: You must install the Open-Horizon CLI in order to use these targets!
 #
 
-publish-service: validate-dockerhubid
+publish-service: validate-dockerhubid validate-org
 	docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
 	ARCH=$(ARCH) \
           SERVICE_NAME="$(SERVICE_NAME)" \
@@ -49,7 +48,7 @@ publish-service: validate-dockerhubid
           DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)"\
           hzn exchange service publish -f service.json --pull-image
 
-publish-all-services: validate-dockerhubid
+publish-all-services: validate-dockerhubid validate-org
 	docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_arm:$(SERVICE_VERSION) -f ./Dockerfile.arm .
 	ARCH=arm \
           SERVICE_NAME="$(SERVICE_NAME)" \
@@ -74,11 +73,19 @@ publish-all-services: validate-dockerhubid
 #
 
 validate-dockerhubid:
-	@if [ -z "${DOCKERHUB_ID}" ]; \
+        @if [ -z "${DOCKERHUB_ID}" ]; \
           then { echo "***** ERROR: \"DOCKERHUB_ID\" is not set!"; exit 1; }; \
           else echo "  NOTE: Using DockerHubID: \"${DOCKERHUB_ID}\""; \
         fi
-	@sleep 1
+        @sleep 1
 
-.PHONY: build dev test clean publish-service publish-all-services validate-dockerhubid
+validate-org:
+        @if [ -z "${HZN_ORG_ID}" ]; \
+          then { echo "***** ERROR: \"HZN_ORG_ID\" is not set!"; exit 1; }; \
+          else echo "  NOTE: Using Exchange Org ID: \"${HZN_ORG_ID}\""; \
+        fi
+        @sleep 1
+
+
+.PHONY: build dev test clean publish-service publish-all-services validate-dockerhubid validate-org
 
diff --git a/shared/mqtt/Makefile b/shared/mqtt/Makefile
--- a/shared/mqtt/Makefile
+++ b/shared/mqtt/Makefile
@@ -44,7 +44,7 @@ clean: validate-dockerhubid
 # NOTE: You must install the Open-Horizon CLI in order to use these targets!
 #
 
-publish-service: validate-dockerhubid
+publish-service: validate-dockerhubid validate-org
 	docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
 	ARCH=$(ARCH) \
           SERVICE_NAME="$(SERVICE_NAME)" \
@@ -52,7 +52,7 @@ publish-service: validate-dockerhubid
           DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)"\
           hzn exchange service publish -f service.json --pull-image
 
-publish-all-services: validate-dockerhubid
+publish-all-services: validate-dockerhubid validate-org
 	docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_arm:$(SERVICE_VERSION) -f ./Dockerfile.arm .
 	ARCH=arm \
           SERVICE_NAME="$(SERVICE_NAME)" \
@@ -83,5 +83,13 @@ validate-dockerhubid:
         fi
 	@sleep 1
 
-.PHONY: build test test-sub test-pub test-end clean publish-service publish-all-services validate-dockerhubid
+validate-org:
+	@if [ -z "${HZN_ORG_ID}" ]; \
+          then { echo "***** ERROR: \"HZN_ORG_ID\" is not set!"; exit 1; }; \
+          else echo "  NOTE: Using Exchange Org ID: \"${HZN_ORG_ID}\""; \
+        fi
+	@sleep 1
+
+
+.PHONY: build test test-sub test-pub test-end clean publish-service publish-all-services validate-dockerhubid validate-org
 
