Prep for multi-arch build, and open-horizon publication.

diff --git a/shared/mqtt/Makefile b/shared/mqtt/Makefile
--- a/shared/mqtt/Makefile
+++ b/shared/mqtt/Makefile
@@ -1,41 +1,23 @@
-# A simple local MQTT broker for Horizon servcies to use
+# A simple local MQTT broker for inter-service communication
 
-# ----------------------------------------------------------------------------
+SERVICE_NAME:="mqtt"
+SERVICE_VERSION:="1.0.0"
 
-# You must always use the Horizon name for architecture (`hzn architecture`)
-export ARCH ?= $(shell hzn architecture)
+#
+# Targets for building, testing and cleaning this service
+#
 
-# Import variables from hzn.json (file is generated by last target in this file)
--include .hzn.json.tmp.mk
+ARCH:=arm
+_ARCH:=$(shell uname -p)
+ifeq ($(_ARCH),'aarch64')
+  ARCH:=arm64
+endif
+ifeq ($(_ARCH),'i386')
+  ARCH:=amd64
+endif
 
-# ----------------------------------------------------------------------------
-
-# Build the docker container
-build: check_id
+build: validate-dockerhubid
 	docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
-
-# Push the docker container to the DockerHub registry
-push: check_id
-	docker push $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION)
-
-# Publish a Horizon service (per service.json) and pull image to get its sha256
-publish-service: check_id
-	DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json --pull-image
-
-# Remove the local container image
-clean: check_id
-	@docker rm -f ${SERVICE_NAME} 2>/dev/null || :
-	@docker rmi $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) 2>/dev/null || :
-	@rm -f .hzn.json.tmp.mk
-
-# ----------------------------------------------------------------------------
-
-
-check_id:
-	@if [ -z "${DOCKERHUB_ID}" ]; \
-          then { echo "***** ERROR: \"DOCKERHUB_ID\" is not set!"; exit 1; }; \
-          else echo "  NOTE: Using DockerHubID: \"${DOCKERHUB_ID}\""; \
-        fi
 
 # How to perform a quick self-test of the MQTT broker
 # - Verified on ubuntu and Rapsbian
@@ -46,7 +28,7 @@ check_id:
 #    3. then in another termninal on the host, publish with: `make test-pub`
 #    4. You should see `Hello, world.` appear in the subscribed terminal
 #    5. Terminate the subscriber with Ctrl-C, then: `make test-end`
-test: check_id
+test: validate-dockerhubid
 	@docker network create mqtt-net 2>/dev/null || :
 	-docker rm -f $(SERVICE_NAME) 2>/dev/null || :
 	docker run --rm -d -p 127.0.0.1:1883:1883 --name $(SERVICE_NAME) --network mqtt-net --network-alias $(SERVICE_NAME) $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION)
@@ -57,11 +39,39 @@ test-pub:
 test-end:
 	-docker rm -f $(SERVICE_NAME)
 
-# ----------------------------------------------------------------------------
+clean: validate-dockerhubid
+	@docker rm -f ${SERVICE_NAME} 2>/dev/null || :
+	@docker rmi $(DOCKERHUB_ID)/$(SERVICE_NAME):$(SERVICE_VERSION) 2>/dev/null || :
+	@docker rmi $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) 2>/dev/null || :
 
-.PHONY: check_id build push publish-service clean dev test test-sub test-pub test-end
+#
+# Targets for publishing this service to an Open-Horizon Exhange
+#
+# NOTE: You must install the Open-Horizon CLI in order to use these targets!
+#
 
-# This imports the variables from hzn.json
-.hzn.json.tmp.mk: hzn.json
-	@ hzn util configconv -f $< > $@
+publish-service: validate-dockerhubid
+	ARCH=$(shell hzn architecture) docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=$(shell hzn architecture) DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json --pull-image
+
+publish-all-services: validate-dockerhubid
+	ARCH=arm SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=arm SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json
+	ARCH=arm64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=arm64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json
+	ARCH=amd64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=amd64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json
+
+#
+# Sanity check targets
+#
+
+validate-dockerhubid:
+	@if [ -z "${DOCKERHUB_ID}" ]; \
+          then { echo "***** ERROR: \"DOCKERHUB_ID\" is not set!"; exit 1; }; \
+          else echo "  NOTE: Using DockerHubID: \"${DOCKERHUB_ID}\""; \
+        fi
+	@sleep 1
+
+.PHONY: build test test-sub test-pub test-end clean publish-service publish-all-services validate-dockerhubid
 
diff --git a/yolocpu/yolocpu/Makefile b/yolocpu/yolocpu/Makefile
--- a/yolocpu/yolocpu/Makefile
+++ b/yolocpu/yolocpu/Makefile
@@ -1,80 +1,104 @@
-# A driver that calls the yolo detector, and pushes data to mqtt and kafka
+# An app that calls the yolo detector, and pushes data to mqtt and kafka
 
-# ----------------------------------------------------------------------------
+SERVICE_NAME:="yolocpu"
+SERVICE_VERSION:="1.0.0"
 
-# You must always use the Horizon name for architecture (`hzn architecture`)
-export ARCH ?= $(shell hzn architecture)
+#
+# Targets for building, developing, testing and cleaning this service
+#
 
-# Import variables from hzn.json (file is generated by last target in this file)
--include .hzn.json.tmp.mk
+ARCH:=arm
+_ARCH:=$(shell uname -p)
+ifeq ($(_ARCH),'aarch64')
+  ARCH:=arm64
+endif
+ifeq ($(_ARCH),'i386')
+  ARCH:=amd64
+endif
 
-# ----------------------------------------------------------------------------
-
-# Build the docker container
-build: check_id
+build: validate-dockerhubid
 	docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
 
-# Push the docker container to the DockerHub registry
-push: check_id
-	docker push $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION)
+# If HZN_DEVICE_ID is not set, use the hostname
+HZN_DEVICE_ID := $(or $(HZN_DEVICE_ID),$(shell sh -c 'host `hostname`'))
 
-# Publish a Horizon service (per service.json) and pull image to get its sha256
-publish-service: check_id
-	DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json --pull-image
+# Get a host routed IP address (used only if CAM_URL not set)
+HOST_IP:=$(word 4, $(shell sh -c 'host `hostname`'))
 
-# Remove the local container image
-clean: check_id
-	@docker rm -f ${SERVICE_NAME} 2>/dev/null || :
-	@docker rmi $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) 2>/dev/null || :
-	@rm -f .hzn.json.tmp.mk
-
-# ----------------------------------------------------------------------------
-
-check_id:
-	@if [ -z "${DOCKERHUB_ID}" ]; \
-          then { echo "***** ERROR: \"DOCKERHUB_ID\" is not set!"; exit 1; }; \
-          else echo "  NOTE: Using DockerHubID: \"${DOCKERHUB_ID}\""; \
-        fi
-
-HOST_INTERFACE:=$(word 5, $(shell sh -c "ip route | grep default | head -1"))
-HOST_IP_ADDRESS:= $(shell sh -c "ip addr | egrep -A 3 'inet .*${HOST_INTERFACE}' | head -1 | grep '    inet ' | sed 's/^    inet //;s|/.*||'")
-dev: check_id
-	@if [ -z "${CAM_URL}" ]; \
-          then echo "  Warning: \"CAM_URL\" is not set! Using default."; \
-          else echo "  NOTE: Using camera URL: ${CAM_URL}"; \
-        fi
+dev: validate-dockerhubid check-cam-url
 	-docker rm -f ${SERVICE_NAME} 2>/dev/null || :
 	docker run -it -v `pwd`:/outside \
-	   -e HOST_IP="${HOST_IP_ADDRESS}" \
 	   -e HZN_DEVICE_ID="${HZN_DEVICE_ID}" \
+	   -e HOST_IP="${HOST_IP}" \
+	   -e CAM_URL="${CAM_URL}" \
 	   -e EVENTSTREAMS_BROKER_URLS="${EVENTSTREAMS_BROKER_URLS}" \
 	   -e EVENTSTREAMS_API_KEY="${EVENTSTREAMS_API_KEY}" \
 	   -e EVENTSTREAMS_PUB_TOPIC="${EVENTSTREAMS_PUB_TOPIC}" \
-	   -e CAM_URL="${CAM_URL}" \
 	   --name ${SERVICE_NAME} \
 	   --network mqtt-net --network-alias ${SERVICE_NAME} \
 	   $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) /bin/sh
 
-test: check_id
-	@if [ -z "${CAM_URL}" ]; \
-          then echo "  Warning: \"CAM_URL\" is not set! Using default."; \
-          else echo "  NOTE: Using camera URL: ${CAM_URL}"; \
-        fi
+test: validate-dockerhubid check-cam-url
 	-docker rm -f ${SERVICE_NAME} 2>/dev/null || :
 	docker run --rm -d \
-	   -e HOST_IP="${HOST_IP_ADDRESS}" \
 	   -e HZN_DEVICE_ID="${HZN_DEVICE_ID}" \
+	   -e HOST_IP="${HOST_IP}" \
+	   -e CAM_URL="${CAM_URL}" \
 	   -e EVENTSTREAMS_BROKER_URLS="${EVENTSTREAMS_BROKER_URLS}" \
 	   -e EVENTSTREAMS_API_KEY="${EVENTSTREAMS_API_KEY}" \
 	   -e EVENTSTREAMS_PUB_TOPIC="${EVENTSTREAMS_PUB_TOPIC}" \
-	   -e CAM_URL="${CAM_URL}" \
 	   --name ${SERVICE_NAME} \
 	   --network mqtt-net --network-alias ${SERVICE_NAME} \
 	   $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION)
 
-# ----------------------------------------------------------------------------
+clean: validate-dockerhubid
+	@docker rm -f ${SERVICE_NAME} 2>/dev/null || :
+	@docker rmi $(DOCKERHUB_ID)/$(SERVICE_NAME):$(SERVICE_VERSION) 2>/dev/null || :
+	@docker rmi $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) 2>/dev/null || :
 
-# This imports the variables from hzn.json
-.hzn.json.tmp.mk: hzn.json
-	@ hzn util configconv -f $< > $@
+#
+# Targets for publishing this service to an Open-Horizon Exhange
+#
+# NOTE: You must install the Open-Horizon CLI in order to use these targets!
+#
+
+publish-service: validate-dockerhubid
+	ARCH=$(shell hzn architecture) docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=$(shell hzn architecture) DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json --pull-image
+
+publish-all-services: validate-dockerhubid
+	ARCH=arm SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=arm SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json
+	ARCH=arm64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=arm64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json
+	ARCH=amd64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=amd64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json
+
+#
+# Sanity check targets
+#
+
+validate-dockerhubid:
+	@if [ -z "${DOCKERHUB_ID}" ]; \
+          then { echo "***** ERROR: \"DOCKERHUB_ID\" is not set!"; exit 1; }; \
+          else echo "  NOTE: Using DockerHubID: \"${DOCKERHUB_ID}\""; \
+        fi
+	@sleep 1
+
+check-cam-url:
+	@if [ -z "${CAM_URL}" ]; \
+          then echo "  Warning: \"CAM_URL\" is not set! Using default."; \
+          else echo "  NOTE: Using camera URL: ${CAM_URL}"; \
+        fi
+	@sleep 1
+
+check-kafka-creds:
+	@if [ -z "${EVENTSTREAMS_BROKER_URLS}" ] || \
+          [ -z "${EVENTSTREAMS_API_KEY}" ] || \
+          [ -z "${EVENTSTREAMS_PUB_TOPIC}" ]; \
+          then echo "  Warning: No EventStreams credentials found! Kafka publication is disabled."; \
+          else echo "  NOTE: Publishing to topic: ${EVENTSTREAMS_PUB_TOPIC}"; \
+        fi
+
+.PHONY: build dev test clean publish-service publish-all-services validate-dockerhubid check-cam-url check-kafka-creds
 
diff --git a/yolocuda/restyolocuda/Makefile b/yolocuda/restyolocuda/Makefile
--- a/yolocuda/restyolocuda/Makefile
+++ b/yolocuda/restyolocuda/Makefile
@@ -1,53 +1,34 @@
-# The yolov3 detector
+# The yolo detector using CUDA
+  
+SERVICE_NAME:="restyolocuda"
+SERVICE_VERSION:="1.0.0"
 
-# ----------------------------------------------------------------------------
+#
+# Targets for building, developing, running and cleaning this service
+#
 
-# You must always use the Horizon name for architecture (`hzn architecture`)
-export ARCH ?= $(shell hzn architecture)
+ARCH:=arm
+_ARCH:=$(shell uname -p)
+ifeq ($(_ARCH),'aarch64')
+  ARCH:=arm64
+endif
+ifeq ($(_ARCH),'i386')
+  ARCH:=amd64
+endif
 
-# Import variables from hzn.json (file is generated by last target in this file)
--include .hzn.json.tmp.mk
-
-# ----------------------------------------------------------------------------
-
-# Build the docker container
-build: check_id
+build: validate-dockerhubid
 	docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
 
-# Push the docker container to the DockerHub registry
-push: check_id
-	docker push $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION)
-
-# Publish a Horizon service (per service.json) and pull image to get its sha256
-publish-service: check_id
-	DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json --pull-image
-
-# Remove the local container image
-clean: check_id
-	@docker rm -f ${SERVICE_NAME} 2>/dev/null || :
-	@docker rmi $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) 2>/dev/null || :
-	@rm -f .hzn.json.tmp.mk
-
-# ----------------------------------------------------------------------------
-
-
-check_id:
-	@if [ -z "${DOCKERHUB_ID}" ]; \
-          then { echo "***** ERROR: \"DOCKERHUB_ID\" is not set!"; exit 1; }; \
-          else echo "  NOTE: Using DockerHubID: \"${DOCKERHUB_ID}\""; \
-        fi
-
-dev: check_id
+dev: validate-dockerhubid
 	-docker rm -f $(SERVICE_NAME) 2>/dev/null || :
-	docker run -it -v `pwd`:/outside \
+	docker run -it \
 	  -p 5252:80 \
 	  --name $(SERVICE_NAME) \
 	  --network mqtt-net --network-alias $(SERVICE_NAME) \
 	  -v `pwd`:/outside \
-	   $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) /bin/bash
+	  $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) /bin/bash
 
-HZN_DEVICE_ID:=
-test: check_id
+test: validate-dockerhubid
 	-docker rm -f $(SERVICE_NAME) 2>/dev/null || :
 	docker run --rm -d \
 	  -p 5252:80 \
@@ -55,11 +36,39 @@ test: check_id
 	  --network mqtt-net --network-alias $(SERVICE_NAME) \
 	  $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION)
 
-# ----------------------------------------------------------------------------
+clean: validate-dockerhubid
+	@docker rm -f ${SERVICE_NAME} 2>/dev/null || :
+	@docker rmi $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) 2>/dev/null || :
 
-.PHONY: check_id build push publish-service clean dev test
+#
+# Targets for publishing this service to an Open-Horizon Exhange
+#
+# NOTE: You must install the Open-Horizon CLI in order to use these targets!
+#
 
-# This imports the variables from hzn.json
-.hzn.json.tmp.mk: hzn.json
-	@ hzn util configconv -f $< > $@
+publish-service: validate-dockerhubid
+	ARCH=$(shell hzn architecture) docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=$(shell hzn architecture) DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json --pull-image
+
+publish-all-services: validate-dockerhubid
+	ARCH=arm SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=arm SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json
+	ARCH=arm64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=arm64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json
+	ARCH=amd64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  docker build -t $(DOCKERHUB_ID)/$(SERVICE_NAME)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
+	ARCH=amd64 SERVICE_NAME="$(SERVICE_NAME)" SERVICE_VERSION="$(SERVICE_VERSION)"  DOCKER_IMAGE_BASE="$(DOCKERHUB_ID)/$(SERVICE_NAME)" hzn exchange service publish -f service.json
+
+#
+# Sanity check targets
+#
+
+validate-dockerhubid:
+	@if [ -z "${DOCKERHUB_ID}" ]; \
+          then { echo "***** ERROR: \"DOCKERHUB_ID\" is not set!"; exit 1; }; \
+          else echo "  NOTE: Using DockerHubID: \"${DOCKERHUB_ID}\""; \
+        fi
+	@sleep 1
+
+
+.PHONY: build dev test clean publish-service publish-all-services validate-dockerhubid
 
